RSWEB_project/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEB_project.Models;

namespace RSWEB_project.Controllers
{
    public class CourseController : Controller
    {
        private readonly AppDbContext _context;

        public CourseController(AppDbContext context)
        {
            _context = context;
        }

        // Index
        public async Task<IActionResult> Index(string teacherString, string searchString, string sortOrder)
        {
            var courses = from c in _context.Course
                          select c;

            courses = courses.Include(c => c.Teacher2).Include(c => c.Teacher1).Include(c => c.Enrollments).ThenInclude(c => c.Student);

            ViewData["TitleSort"] = String.IsNullOrEmpty(sortOrder) ? "TitleD" : "";
            ViewData["CreditsSort"] = sortOrder == "Credits" ? "CreditsD" : "Credits";
            ViewData["SemesterSort"] = sortOrder == "Semester" ? "SemesterD" : "Semester";
            ViewData["ProgrammeSort"] = sortOrder == "Programme" ? "ProgrammeD" : "Programme";
            ViewData["LevelSort"] = sortOrder == "EducationLevel" ? "EducationLevelD" : "EducationLevel";
            ViewData["FTidSort"] = sortOrder == "FTid" ? "FTidD" : "FTid";
            ViewData["STidSort"] = sortOrder == "STid" ? "STidD" : "STid";

            courses = sortOrder switch
            {
                "Credits" => courses.OrderBy(s => s.Credits),
                "CreditsD" => courses.OrderByDescending(s => s.Credits),
                "Semester" => courses.OrderBy(s => s.Semester),
                "SemesterD" => courses.OrderByDescending(s => s.Semester),
                "Programme" => courses.OrderBy(s => s.Programme),
                "ProgrammeD" => courses.OrderByDescending(s => s.Programme),
                "EducationLevel" => courses.OrderBy(s => s.EducationLevel),
                "EducationLevelD" => courses.OrderByDescending(s => s.EducationLevel),
                "FTid" => courses.OrderBy(s => s.FirstTeacherId),
                "FTidD" => courses.OrderByDescending(s => s.FirstTeacherId),
                "STid" => courses.OrderBy(s => s.SecondTeacherId),
                "STidD" => courses.OrderByDescending(s => s.SecondTeacherId),
                "TitleD" => courses.OrderByDescending(s => s.Title),
                _ => courses.OrderBy(c => c.Title),
            };

            if (!String.IsNullOrEmpty(searchString))
            {
                int x = 0;
                Int32.TryParse(searchString, out x);
                courses = courses.Where(s => s.Title.Contains(searchString) || s.Semester == x || s.Programme.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(teacherString))
            {
                // var  teachers = _context.Teacher.Where(m=>m.FirstName.Contains(teacherString));

                int y = 0;
                Int32.TryParse(teacherString, out y);
                courses = courses.Where(s => s.FirstTeacherId == y || s.SecondTeacherId == y || s.Teacher1.FirstName.Contains(teacherString) || s.Teacher2.FirstName.Contains(teacherString));

            }

            return View(await courses.ToListAsync());
        }

        // Details/id
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(t => t.Teacher1)
                .Include(t => t.Teacher2)
                .Include(c => c.Enrollments)
                .ThenInclude(c => c.Student)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Create
        public IActionResult Create()
        {
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");

            return View();
        }

        // Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Edit/id
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);

            if (course == null)
            {
                return NotFound();
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Delete/id
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Teacher1)
                .Include(c => c.Teacher2)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }

        public async Task<IActionResult> TeacherIndex(int teacherId)
        {
            var courses = from c in _context.Course
                          select c;

            courses = courses.Include(c => c.Teacher2).Include(c => c.Teacher1).Include(c => c.Enrollments).ThenInclude(c => c.Student);
            courses = courses.Where(c => c.Teacher1.Id.Equals(teacherId) || c.Teacher2.Id.Equals(teacherId));

            ViewData["TeacherId"] = teacherId;

            // for the _NonAdminLayout
            Teacher t = await _context.Teacher.FindAsync(teacherId);
            ViewData["ProfilePicture"] = t.ProfilePicture;
            ViewData["FullName"] = t.FullName;

            return View(await courses.ToListAsync());
        }
    }
}

RSWEB_project/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEB_project.Models;
using RSWEB_project.ViewModels;

namespace RSWEB_project.Controllers
{
    public class TeacherController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public TeacherController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // Index
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
           var teachers = from m in _context.Teacher
                          select m;

            teachers = teachers.Include(t => t.Courses1).Include(t => t.Courses2);

            ViewData["FNameSort"] = String.IsNullOrEmpty(sortOrder) ? "FNameD" : "";
            ViewData["LNameSort"] = String.IsNullOrEmpty(sortOrder) ? "LNameD" : "";
            ViewData["DegreeSort"] = sortOrder=="Degree" ? "DegreeD" : "Degree";
            ViewData["RankSort"] = sortOrder == "Rank" ? "RankD" : "Rank";
            ViewData["NumSort"] = sortOrder == "Number" ? "NumberD" : "Number";
            ViewData["DateSort"] = sortOrder == "HireDate" ? "HireDateD" : "HireDate";

            teachers = sortOrder switch
            {
                "Degree" => teachers.OrderBy(t => t.Degree),
                "DegreeD" => teachers.OrderByDescending(t => t.Degree),
                "Rank" => teachers.OrderBy(t => t.AcademicRank),
                "RankD" => teachers.OrderByDescending(t => t.AcademicRank),
                "Number" => teachers.OrderBy(t => t.OfficeNumber),
                "NumberD" => teachers.OrderByDescending(t => t.OfficeNumber),
                "HireDate" => teachers.OrderBy(t => t.HireDate),
                "HireDateD" => teachers.OrderByDescending(t => t.HireDate),
                "FNameD" => teachers.OrderByDescending(t => t.FirstName),
                "LNameD" => teachers.OrderByDescending(t => t.LastName),
                _ => teachers.OrderBy(t => t.FirstName),
            };

            if (!String.IsNullOrEmpty(searchString))
            {
                teachers = teachers.Where(s => s.FirstName.Contains(searchString) || s.LastName.Contains(searchString) || s.AcademicRank.Contains(searchString) || s.Degree.Contains(searchString));
            }
          
            return View(await teachers.ToListAsync());
        }

        // Details/id
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.Include(t=>t.Courses1).Include(t=>t.Courses2)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // Create
        public IActionResult Create()
        {
            return View();
        }

        // Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeacherViewModel ViewModel)
        {
            if (ModelState.IsValid)
            {
                if(ViewModel.ProfileImage != null)
                {
                    string uniqueFileName = UploadedFile(ViewModel);
                    ViewModel.Teacher.ProfilePicture = uniqueFileName;
                }

                else
                {
                    ViewModel.Teacher.ProfilePicture = "_default.png";
                }

                _context.Add(ViewModel.Teacher);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(ViewModel);
        }

        // Edit/id
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }

            TeacherViewModel ViewModel = new TeacherViewModel
            {
                Teacher = teacher,
                ProfileImage = null
            };

            return View(ViewModel);
        }

        // Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TeacherViewModel ViewModel)
        {
            if (id != ViewModel.Teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if(ViewModel.ProfileImage != null)
                    {
                        string uniqueFileName = UploadedFile(ViewModel);
                        ViewModel.Teacher.ProfilePicture = uniqueFileName;
                    }

                    _context.Update(ViewModel.Teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(ViewModel.Teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(ViewModel);
        }

        // Delete/id
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.Id == id);
        }

        public async Task<IActionResult> TeacherLogin()
        {
            var teachers = from m in _context.Teacher
                           select m;

            return View(await teachers.ToListAsync());
        }

        private string UploadedFile(TeacherViewModel model)
        {
            string uniqueFileName = null;

            if (model.ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.ProfileImage.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfileImage.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

RSWEB_project/Views/Course/Create.cshtml
@model Course

@{
    ViewData["Title"] = "Create";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Index">BACK</a>
</div>

<hr />

<form asp-action="Create" style="width: 25%; margin: auto;">
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Credits" class="control-label"></label>
        <input asp-for="Credits" class="form-control" />
        <span asp-validation-for="Credits" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Semester" class="control-label"></label>
        <input asp-for="Semester" class="form-control" />
        <span asp-validation-for="Semester" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Programme" class="control-label"></label>
        <input asp-for="Programme" class="form-control" />
        <span asp-validation-for="Programme" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EducationLevel" class="control-label"></label>
        <input asp-for="EducationLevel" class="form-control" />
        <span asp-validation-for="EducationLevel" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstTeacherId" class="control-label">First teacher</label>
        <select asp-for="FirstTeacherId" class="form-control" asp-items="ViewBag.FirstTeacherId">
            <option value="" disabled selected></option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="SecondTeacherId" class="control-label">Second teacher</label>
        <select asp-for="SecondTeacherId" class="form-control" asp-items="ViewBag.SecondTeacherId">
            <option value="" disabled selected></option>
        </select>
    </div>
    <div>
        <input type="submit" value="Add Course" class="btn btn-success" />
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEB_project/Views/Course/Delete.cshtml
@model Course

@{
    ViewData["Title"] = "Delete";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Details" asp-route-id="@Model.Id">BACK</a>
</div>

<hr />

<dl class="row" style="width: 59%; margin-left: 39%;">
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Title)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Title)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Credits)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Credits)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Semester)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Semester)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Programme)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Programme)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.EducationLevel)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.EducationLevel)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayName("First Teacher")
    </dt>
    <dd class="col-sm-9">
        <a asp-controller="Teacher" asp-action="Details" asp-route-id="@Model.FirstTeacherId">@Html.DisplayFor(ModelItem => Model.Teacher1.FullName)</a>
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayName("Second Teacher")
    </dt>
    <dd class="col-sm-9">
        <a asp-controller="Teacher" asp-action="Details" asp-route-id="@Model.SecondTeacherId">@Html.DisplayFor(ModelItem => Model.Teacher2.FullName)</a>
    </dd>
</dl>

<br />

<h5 style="text-align: center; width: 100%;">Are you sure?</h5>
<form asp-action="Delete" style="width: 100%; text-align: center; display: inline-block;">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="DELETE COURSE" class="btn btn-danger" />
</form>

RSWEB_project/Views/Course/Details.cshtml
@model Course

@{
    ViewData["Title"] = "Details";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Index">BACK</a>
    <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model.Id">EDIT</a>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">DELETE</a>
</div>

<hr />

<dl class="row" style="width: 59%; margin-left: 39%;">
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Title)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Title)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Credits)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Credits)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Semester)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Semester)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Programme)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Programme)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.EducationLevel)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.EducationLevel)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Teacher1)
    </dt>
    <dd class="col-sm-9">
        <a asp-controller="Teacher" asp-action="Details" asp-route-id="@Model.FirstTeacherId">@Html.DisplayFor(ModelItem => Model.Teacher1.FullName)</a>
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Teacher2)
    </dt>
    <dd class="col-sm-9">
        <a asp-controller="Teacher" asp-action="Details" asp-route-id="@Model.SecondTeacherId">@Html.DisplayFor(ModelItem => Model.Teacher2.FullName)</a>
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayName("Enrolled Students")
    </dt>
    <dd class="col-sm-9">
        @foreach (var e in Model.Enrollments)
        {
            if (e.FinishDate == null)
            {
                <a asp-controller="Enrollment" asp-action="Details" asp-route-id="@e.Id">
                    @Html.DisplayFor(modelItem => e.Student.FullName)
                </a>
                <br />
            }
        }
    </dd>
    <dt class="col-sm-3"></dt>
    <dd class="col-sm-9">
        <a class="btn btn-success" style="min-width: 19%;" asp-controller="Enrollment" asp-action="AdminCreate">
            Add Enrollments
        </a>
    </dd>
    <dt class="col-sm-3"></dt>
    <dd class="col-sm-9">
        <a class="btn btn-info" style="min-width: 19%;" asp-controller="Enrollment" asp-action="AdminEditMultiple" asp-route-courseId="@Model.Id">
            Unenroll Students
        </a>
    </dd>
</dl>

RSWEB_project/Views/Course/Index.cshtml
@model IEnumerable<Course>

@{
    ViewData["Title"] = "Index";
    ViewData["CurrentPage"] = "Courses";
}

<form asp-controller="Course" asp-action="Index" method="get" style="margin-bottom: 16px; margin-left: 3%; width: 44%; display: inline-block;">
    <input class="input-global" type="text" name="teacherString" placeholder=" Teacher or TeacherID" />
    <input class="input-global" type="text" name="SearchString" placeholder=" Title or Semester or Programme" style="width: 28%;">
    <input class="input-global" type="submit" value="Search" />
</form>

<a style="display: inline-block; font-size: 18px;" asp-action="Create">Add new entry</a>

<div class="table-responsive">
    <table class="table table-striped table-borderless table-hover-custom">
        <thead class="thead-dark">
            <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["TitleSort"]">
                        @Html.DisplayNameFor(model => model.Title)
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["CreditsSort"]">
                        @Html.DisplayNameFor(model => model.Credits)
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["SemesterSort"]">
                        @Html.DisplayNameFor(model => model.Semester)
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["ProgrammeSort"]">
                        @Html.DisplayNameFor(model => model.Programme)
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["LevelSort"]">
                        @Html.DisplayNameFor(model => model.EducationLevel)
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["FTidSort"]">
                        @Html.DisplayName("First Teacher")
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["STidSort"]">
                        @Html.DisplayName("Second Teacher")
                    </a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Credits)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Semester)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Programme)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EducationLevel)
                    </td>
                    <td>
                        <a asp-controller="Teacher" asp-action="Details" asp-route-id="@item.FirstTeacherId">
                            @Html.DisplayFor(modelItem => item.Teacher1.FullName)
                        </a>
                    </td>
                    <td>
                        <a asp-controller="Teacher" asp-action="Details" asp-route-id="@item.SecondTeacherId">

                            @Html.DisplayFor(modelItem => item.Teacher2.FullName)
                        </a>
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">View Details &raquo;</a>
                    </td>
                </tr>
                }
        </tbody>
    </table>
</div>

RSWEB_project/Views/Course/TeacherIndex.cshtml
@model IEnumerable<Course>

@{
    ViewData["Title"] = "TeacherIndex";
    Layout = "_NonAdminLayout";
}

<form asp-controller="Course" asp-action="Index" method="get" style="margin-bottom: 16px; margin-left: 3%; width: 44%; display: inline-block; visibility: hidden;">
    <input class="input-global" type="text" name="CourseName" placeholder=" Course" />
    <input class="input-global" type="submit" value="Search" />
</form>

<div class="text-center" style="display: inline-block;">
    <p style="font-size: 19px;">Courses teaching:</p>
</div>

<div style="display: inline-block; float: right; margin-right: 10%;">
    <a class="btn btn-primary" asp-controller="Teacher" asp-action="TeacherLogin">BACK</a>
</div>

<div class="table-responsive">
    <table class="table table-striped table-borderless table-hover-custom">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Credits)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Semester)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Programme)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => c.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(model => c.Credits)
                    </td>
                    <td>
                        @Html.DisplayFor(model => c.Semester)
                    </td>
                    <td>
                        @Html.DisplayFor(model => c.Programme)
                    </td>
                    <td>
                        <a asp-controller="Enrollment" asp-action="TeacherCourseIndex" asp-route-CourseId="@c.Id"
                           asp-route-Year="" asp-route-TeacherId="@ViewData["TeacherId"]">
                            View Students &raquo;
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>