RSWEB_project/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RSWEB_project.Models
{
    public class Enrollment
    {
        [Key]
        [Required]
        public long Id { get; set; }

        [Required]
        [ForeignKey("Courseid")]
        public int? CourseId { get; set; }

        [Required]
        [ForeignKey("Studentid")]
        public long? StudentId { get; set; }

        [Required]
        [StringLength(10)]
        public string Semester { get; set; }

        public int Year { get; set; }

        [Range(6, 10)]
        public int? Grade { get; set; }

        [StringLength(255)]
        [Display(Name = "Seminal URL")]
        public string SeminalUrl { get; set; }

        [StringLength(255)]
        [Display(Name = "Project URL")]
        public string ProjectUrl { get; set; }

        [Display(Name = "Exam Points")]
        public int? ExamPoints { get; set; }

        [Display(Name = "Seminal Points")]
        public int? SeminalPoints { get; set; }

        [Display(Name = "Project Points")]
        public int? ProjectPoints { get; set; }

        [Display(Name = "Additional Points")]
        public int? AdditionalPoints { get; set; }

        [Display(Name = "Finish Date")]
        [DataType(DataType.Date)]
        public DateTime? FinishDate { get; set; }

        public Course Course { get; set; }
        public Student Student { get; set; }
    }
}

RSWEB_project/ViewModels/EnrollmentsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RSWEB_project.ViewModels
{
    public class EnrollmentsViewModel
    {
        [Required]
        public int Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Required]
        public int CourseId { get; set; }

        [Required]
        public IList<long> StudentIds { get; set; }
    }
}

RSWEB_project/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using RSWEB_project.Models;
using RSWEB_project.ViewModels;

namespace RSWEB_project.Controllers
{
    public class EnrollmentController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EnrollmentController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // Index (IMPLEMENT SORTING)
        public async Task<IActionResult> Index()
        {
            var onlineCoursesContext = _context.Enrollment.Include(e => e.Course).Include(e => e.Student);

            return View(await onlineCoursesContext.ToListAsync());
        }

        // Details/id
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // Create
        public IActionResult Create()
        {
            ViewData["Courseid"] = new SelectList(_context.Course, "Id", "Title");
            ViewData["Studentid"] = new SelectList(_context.Student, "Id", "FullName");

            return View();
        }

        // Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CourseId,StudentId,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["Courseid"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["Studentid"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);

            return View(enrollment);
        }

        // Edit/id
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.FindAsync(id);

            if (enrollment == null)
            {
                return NotFound();
            }

            ViewData["Courseid"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["Studentid"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);

            return View(enrollment);
        }

        // Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CourseId,StudentId,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (id != enrollment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["Courseid"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["Studentid"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);

            return View(enrollment);
        }

        // Delete/id
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var enrollment = await _context.Enrollment.FindAsync(id);
            _context.Enrollment.Remove(enrollment);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // EnrollmentExists (private method)
        private bool EnrollmentExists(long id)
        {
            return _context.Enrollment.Any(e => e.Id == id);
        }

        // TeacherCourseIndex
        [HttpGet]
        public async Task<IActionResult> TeacherCourseIndex([FromQuery] int CourseId, [FromQuery] string Year, [FromQuery] int TeacherId)
        {
            var enrollments = _context.Enrollment.Include(e => e.Course).Include(e => e.Student).AsQueryable();

            string year;

            if (!String.IsNullOrEmpty(Year))
            {
                year = Year;
            }

            else
            {
                year = DateTime.Now.Year.ToString();
            }

            enrollments = enrollments.Where(e => e.Course.Id.Equals(CourseId) && e.Year.ToString().Equals(year));
            enrollments = enrollments.OrderBy(e => e.Student.FirstName);

            ViewData["CourseId"] = CourseId;
            ViewData["TeacherId"] = TeacherId;

            // for the _NonAdminLayout
            Teacher t = await _context.Teacher.FindAsync(TeacherId);
            ViewData["ProfilePicture"] = t.ProfilePicture;
            ViewData["FullName"] = t.FullName;

            return View(await enrollments.ToListAsync());
        }

        // TeacherCourseEdit
        public async Task<IActionResult> TeacherCourseEdit(long? id, int TeacherId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.FindAsync(id);

            if (enrollment == null)
            {
                return NotFound();
            }

            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);
            ViewData["TeacherId"] = TeacherId; // for previous page

            // for the _NonAdminLayout
            Teacher t = await _context.Teacher.FindAsync(TeacherId);
            ViewData["ProfilePicture"] = t.ProfilePicture;
            ViewData["FullName"] = t.FullName;

            return View(enrollment);
        }

        // TeacherCourseEdit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TeacherCourseEdit(long Id, int TeacherId, [Bind("Id,CourseId,StudentId,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (Id != enrollment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("TeacherCourseIndex", new { CourseId = enrollment.CourseId, TeacherId = TeacherId });
            }

            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);
            ViewData["TeacherId"] = TeacherId; // for previous page

            // for the _NonAdminLayout
            Teacher t = await _context.Teacher.FindAsync(TeacherId);
            ViewData["ProfilePicture"] = t.ProfilePicture;
            ViewData["FullName"] = t.FullName;

            return View(enrollment);
        }

        // StudentIndex
        public async Task<IActionResult> StudentIndex(long StudentId)
        {
            var enrollments = _context.Enrollment.Include(e => e.Course).Include(e => e.Student).AsQueryable();

            enrollments = enrollments.Where(e => e.StudentId.Equals(StudentId));
            enrollments = enrollments.OrderByDescending(e => e.Semester);

            // for the _NonAdminLayout
            Student s = await _context.Student.FindAsync(StudentId);
            ViewData["ProfilePicture"] = s.ProfilePicture;
            ViewData["FullName"] = s.FullName;

            return View(await enrollments.ToListAsync());
        }

RSWEB_project/Views/Enrollment/AdminCreate.cshtml
@model EnrollmentsViewModel

@{
    ViewData["Title"] = "AdminCreate";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Index">BACK</a>
</div>

<hr />

<form asp-action="AdminCreate" style="width: 25%; margin: auto;">
    <div class="form-group">
        <label asp-for="CourseId" class="control-label">Course</label>
        <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseIds">
            <option value="" disabled selected></option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="StudentIds" class="control-label">Students</label>
        <select asp-for="StudentIds" class="form-control js-example-basic-multiple" multiple="multiple" asp-items="ViewBag.StudentIds">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Semester" class="control-label"></label>
        <input asp-for="Semester" class="form-control" />
        <span asp-validation-for="Semester" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label"></label>
        <input asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Add Enrollments" class="btn btn-success" />
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/lib/select2/js/select2.js"></script>
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
        });
    </script>
}

RSWEB_project/Views/Enrollment/AdminEdit.cshtml
@model Enrollment

@{
    ViewData["Title"] = "AdminEdit";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Details" asp-route-id="@Model.Id">BACK</a>
</div>

<hr />

<form asp-action="AdminEdit" style="width: 25%; margin: auto;">

    <input type="hidden" asp-for="Id" />
    <select asp-for="CourseId" class="form-control" hidden></select>
    <select asp-for="StudentId" class="form-control" hidden></select>
    <input asp-for="Semester" class="form-control" hidden />
    <input asp-for="Year" class="form-control" hidden />
    <input asp-for="Grade" class="form-control" hidden />
    <input asp-for="SeminalUrl" class="form-control" hidden />
    <input asp-for="ProjectUrl" class="form-control" hidden />
    <input asp-for="ExamPoints" class="form-control" hidden />
    <input asp-for="SeminalPoints" class="form-control" hidden />
    <input asp-for="ProjectPoints" class="form-control" hidden />
    <input asp-for="AdditionalPoints" class="form-control" hidden />

    <div class="form-group">
        <label asp-for="FinishDate" class="control-label"></label>
        <input asp-for="FinishDate" class="form-control" />
        <span asp-validation-for="FinishDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Save Changes" class="btn btn-success" />
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEB_project/Views/Enrollment/AdminEditMultiple.cshtml
@model UnenrollMultipleViewModel

@{
    ViewData["Title"] = "AdminEditMultiple";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Index">BACK - Enrollments</a>
</div>

<hr style="width: 20%;"/>

<form asp-action="AdminEditMultiple" style="width: 25%; margin: auto;" method="get">
    <div class="form-group">
        <label asp-for="CourseId" class="control-label">Courses</label>
        <select asp-for="CourseId" class="form-control" asp-items="@ViewBag.Courses">
            <option value="" disabled selected></option>
        </select>
        <span asp-validation-for="CourseId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label"></label>
        <input asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Get Enrollments" class="btn btn-outline-secondary" />
    </div>
</form>

<hr style="width: 20%;"/>

<form asp-action="AdminEditMultiple" style="width: 25%; margin: auto;" method="post">
    <div class="form-group">
        <label asp-for="EnrollmentIds" class="control-label">Enrollments</label>
        <select asp-for="EnrollmentIds" class="form-control js-example-basic-multiple" multiple="multiple" asp-items="@ViewBag.Enrollments">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="FinishDate" class="control-label"></label>
        <input asp-for="FinishDate" class="form-control" />
        <span asp-validation-for="FinishDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Save Changes" class="btn btn-success" />
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/lib/select2/js/select2.js"></script>
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
        });
    </script>
}

RSWEB_project/Views/Enrollment/Create.cshtml
@model Enrollment

@{
    ViewData["Title"] = "Create";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Index">BACK</a>
</div>

<hr />

<form asp-action="Create" style="width: 25%; margin: auto;">
    <div class="form-group">
        <label asp-for="CourseId" class="control-label">Course</label>
        <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Courseid" placeholder="">
            <option value="" disabled selected></option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="StudentId" class="control-label">Student</label>
        <select asp-for="StudentId" class="form-control" asp-items="ViewBag.Studentid" placeholder="">
            <option value="" disabled selected></option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Semester" class="control-label"></label>
        <input asp-for="Semester" class="form-control" />
        <span asp-validation-for="Semester" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label"></label>
        <input asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Grade" class="control-label"></label>
        <input asp-for="Grade" class="form-control" />
        <span asp-validation-for="Grade" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SeminalUrl" class="control-label"></label>
        <input asp-for="SeminalUrl" class="form-control" />
        <span asp-validation-for="SeminalUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ProjectUrl" class="control-label"></label>
        <input asp-for="ProjectUrl" class="form-control" />
        <span asp-validation-for="ProjectUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ExamPoints" class="control-label"></label>
        <input asp-for="ExamPoints" class="form-control" />
        <span asp-validation-for="ExamPoints" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SeminalPoints" class="control-label"></label>
        <input asp-for="SeminalPoints" class="form-control" />
        <span asp-validation-for="SeminalPoints" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ProjectPoints" class="control-label"></label>
        <input asp-for="ProjectPoints" class="form-control" />
        <span asp-validation-for="ProjectPoints" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="AdditionalPoints" class="control-label"></label>
        <input asp-for="AdditionalPoints" class="form-control" />
        <span asp-validation-for="AdditionalPoints" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FinishDate" class="control-label"></label>
        <input asp-for="FinishDate" class="form-control" />
        <span asp-validation-for="FinishDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Add Enrollment" class="btn btn-success" />
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEB_project/Views/Enrollment/Delete.cshtml
@model Enrollment

@{
    ViewData["Title"] = "Delete";
}

<div style="text-align: center;">
    <a class="btn btn-primary" asp-action="Details" asp-route-id="@Model.Id">BACK</a>
</div>

<hr />

<dl class="row" style="width: 59%; margin-left: 39%;">
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Course)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Course.Title)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Student)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Student.FirstName)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Semester)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Semester)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Year)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Year)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.Grade)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.Grade)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.SeminalUrl)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.SeminalUrl)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.ProjectUrl)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.ProjectUrl)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.ExamPoints)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.ExamPoints)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.SeminalPoints)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.SeminalPoints)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.ProjectPoints)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.ProjectPoints)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.AdditionalPoints)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.AdditionalPoints)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.FinishDate)
    </dt>
    <dd class="col-sm-9">
        @Html.DisplayFor(model => model.FinishDate)
    </dd>
</dl>

<br />

<h5 style="text-align: center; width: 100%;">Are you sure?</h5>
<form asp-action="Delete" style="width: 100%; text-align: center; display: inline-block;">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="DELETE ENROLLMENT" class="btn btn-danger" />
</form>

RSWEB_project/Views/Enrollment/Index.cshtml
@model IEnumerable<Enrollment>

@{
    ViewData["Title"] = "Index";
    ViewData["CurrentPage"] = "Enrollments";
}

<form asp-controller="Enrollment" asp-action="Index" method="get" style="margin-bottom: 16px; margin-left: 3%; width: 44%; display: inline-block; visibility: hidden;">
    <input class="input-global" type="text" name="SearchString" placeholder="" style="width: 25%;">
    <input class="input-global" type="submit" value="Search" />
</form>

<a style="display: inline-block; font-size: 18px;" asp-action="AdminCreate">Add new entry</a>

<div style="display: inline-block; float: right; margin-right: 10%;">
    <a class="btn btn-info" asp-action="AdminEditMultiple">Unenroll Students</a>
</div>

<div class="table-responsive">
    <table class="table table-striped table-borderless table-hover-custom">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayName("Course")
                </th>
                <th>
                    @Html.DisplayName("Student")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Semester)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Year)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Grade)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SeminalUrl)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProjectUrl)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExamPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SeminalPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProjectPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AdditionalPoints)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FinishDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Student.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Semester)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SeminalUrl)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProjectUrl)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExamPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SeminalPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProjectPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AdditionalPoints)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FinishDate)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">View Details &raquo; </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>