RSWEB_project/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEB_project.Models;

namespace RSWEB_project.Controllers
{
    public class CourseController : Controller
    {
        private readonly AppDbContext _context;

        public CourseController(AppDbContext context)
        {
            _context = context;
        }

        // Index
        public async Task<IActionResult> Index(string teacherString, string searchString, string sortOrder)
        {
            var courses = from c in _context.Course
                          select c;

            courses = courses.Include(c => c.Teacher2).Include(c => c.Teacher1).Include(c => c.Enrollments).ThenInclude(c => c.Student);

            ViewData["TitleSort"] = String.IsNullOrEmpty(sortOrder) ? "TitleD" : "";
            ViewData["CreditsSort"] = sortOrder == "Credits" ? "CreditsD" : "Credits";
            ViewData["SemesterSort"] = sortOrder == "Semester" ? "SemesterD" : "Semester";
            ViewData["ProgrammeSort"] = sortOrder == "Programme" ? "ProgrammeD" : "Programme";
            ViewData["LevelSort"] = sortOrder == "EducationLevel" ? "EducationLevelD" : "EducationLevel";
            ViewData["FTidSort"] = sortOrder == "FTid" ? "FTidD" : "FTid";
            ViewData["STidSort"] = sortOrder == "STid" ? "STidD" : "STid";

            courses = sortOrder switch
            {
                "Credits" => courses.OrderBy(s => s.Credits),
                "CreditsD" => courses.OrderByDescending(s => s.Credits),
                "Semester" => courses.OrderBy(s => s.Semester),
                "SemesterD" => courses.OrderByDescending(s => s.Semester),
                "Programme" => courses.OrderBy(s => s.Programme),
                "ProgrammeD" => courses.OrderByDescending(s => s.Programme),
                "EducationLevel" => courses.OrderBy(s => s.EducationLevel),
                "EducationLevelD" => courses.OrderByDescending(s => s.EducationLevel),
                "FTid" => courses.OrderBy(s => s.FirstTeacherId),
                "FTidD" => courses.OrderByDescending(s => s.FirstTeacherId),
                "STid" => courses.OrderBy(s => s.SecondTeacherId),
                "STidD" => courses.OrderByDescending(s => s.SecondTeacherId),
                "TitleD" => courses.OrderByDescending(s => s.Title),
                _ => courses.OrderBy(c => c.Title),
            };

            if (!String.IsNullOrEmpty(searchString))
            {
                int x = 0;
                Int32.TryParse(searchString, out x);
                courses = courses.Where(s => s.Title.Contains(searchString) || s.Semester == x || s.Programme.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(teacherString))
            {
                // var  teachers = _context.Teacher.Where(m=>m.FirstName.Contains(teacherString));

                int y = 0;
                Int32.TryParse(teacherString, out y);
                courses = courses.Where(s => s.FirstTeacherId == y || s.SecondTeacherId == y || s.Teacher1.FirstName.Contains(teacherString) || s.Teacher2.FirstName.Contains(teacherString));

            }

            return View(await courses.ToListAsync());
        }

        // Details/id
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(t => t.Teacher1)
                .Include(t => t.Teacher2)
                .Include(c => c.Enrollments)
                .ThenInclude(c => c.Student)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Create
        public IActionResult Create()
        {
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");

            return View();
        }

        // Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Edit/id
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);

            if (course == null)
            {
                return NotFound();
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Delete/id
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Teacher1)
                .Include(c => c.Teacher2)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "id", "FullName", course.SecondTeacherId);

            return View(course);
        }

        // Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }

        public async Task<IActionResult> TeacherIndex(int teacherId)
        {
            var courses = from c in _context.Course
                          select c;

            courses = courses.Include(c => c.Teacher2).Include(c => c.Teacher1).Include(c => c.Enrollments).ThenInclude(c => c.Student);
            courses = courses.Where(c => c.Teacher1.Id.Equals(teacherId) || c.Teacher2.Id.Equals(teacherId));

            ViewData["TeacherId"] = teacherId;

            // for the _NonAdminLayout
            Teacher t = await _context.Teacher.FindAsync(teacherId);
            ViewData["ProfilePicture"] = t.ProfilePicture;
            ViewData["FullName"] = t.FullName;

            return View(await courses.ToListAsync());
        }
    }
}

RSWEB_project/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEB_project.Models;
using RSWEB_project.ViewModels;

namespace RSWEB_project.Controllers
{
    public class StudentController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public StudentController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // Index
        public async Task<IActionResult> Index(string courseString, string searchString, string sortOrder)
        {
            var students = from m in _context.Student
                           select m;

            students = students.Include(s => s.Enrollments).ThenInclude(s => s.Course);

            //on every call, set one field & reset all other fields.
            ViewData["FNameSort"] = String.IsNullOrEmpty(sortOrder) ? "FNameD" : "";
            ViewData["CreditsSort"] = sortOrder == "Credits" ? "CreditsD" : "Credits";
            ViewData["LNameSort"] = String.IsNullOrEmpty(sortOrder) ? "LNameD" : "";
            ViewData["StudentIdSort"] = sortOrder == "StudentId" ? "StudentIdD" : "StudentId";
            ViewData["DateSort"] = sortOrder == "Date" ? "DateD" : "Date";
            ViewData["SemSort"] = sortOrder == "Semester" ? "SemesterD" : "Semester";
            ViewData["LevelSort"] = sortOrder == "EducationLevel" ? "EducationLevelD" : "EducationLevel";

            students = sortOrder switch
            {
                "FNameD" => students.OrderByDescending(s => s.FirstName),
                "Credits" => students.OrderBy(s => s.AcquiredCredits),
                "CreditsD" => students.OrderByDescending(s => s.AcquiredCredits),
                "StudentId" => students.OrderBy(s => s.StudentId),
                "StudentIdD" => students.OrderByDescending(s => s.StudentId),
                "Date" => students.OrderBy(s => s.EnrollmentDate),
                "DateD" => students.OrderByDescending(s => s.EnrollmentDate),
                "Semester" => students.OrderBy(s => s.CurrentSemester),
                "SemesterD" => students.OrderByDescending(s => s.CurrentSemester),
                "LNameD" => students.OrderByDescending(s => s.LastName),
                "EducationLevel" => students.OrderBy(s => s.EducationLevel),
                "EducationLevelD" => students.OrderByDescending(s => s.EducationLevel),
                _ => students.OrderBy(s => s.FirstName),
            };

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.StudentId.Contains(searchString) || s.FirstName.Contains(searchString) || s.LastName.Contains(searchString));

            }

            if (!String.IsNullOrEmpty(courseString))
            {
                var enrollments = _context.Enrollment.AsQueryable();
                enrollments = enrollments.Where(m => m.Course.Title.Contains(courseString));
                students = students.Where(s => s.Enrollments.Any(e => e.Course.Title == courseString));

            }

            return View(await students.ToListAsync());
        }

        // Details
        public async Task<IActionResult> Details(long? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.Include(s => s.Enrollments).ThenInclude(s => s.Course)
                // .Include(s => s.Enrollments.Where(e => e.Studentid == id))
                .FirstOrDefaultAsync(s => s.Id == id);

            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }


        // Create
        public IActionResult Create()
        {
            return View();
        }

        // Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StudentViewModel ViewModel)
        {
            if (ModelState.IsValid)
            {
                if(ViewModel.ProfileImage != null)
                {
                    string uniqueFileName = UploadedFile(ViewModel);
                    ViewModel.Student.ProfilePicture = uniqueFileName;
                }

                else
                {
                    ViewModel.Student.ProfilePicture = "_default.png";
                }

                _context.Add(ViewModel.Student);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(ViewModel);
        }

        // Edit/id
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }

            StudentViewModel ViewModel = new StudentViewModel
            {
                Student = student,
                ProfileImage = null
            };

            return View(ViewModel);
        }

        // Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, StudentViewModel ViewModel)
        {
            if (id != ViewModel.Student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if(ViewModel.ProfileImage != null)
                    {
                        string uniqueFileName = UploadedFile(ViewModel);
                        ViewModel.Student.ProfilePicture = uniqueFileName;
                    }

                    _context.Update(ViewModel.Student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(ViewModel.Student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(ViewModel);
        }

        // Delete/id
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // Delete/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id)
        {
            var student = await _context.Student.FindAsync(id);

            _context.Student.Remove(student);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(long id)
        {
            return _context.Student.Any(e => e.Id == id);
        }

        public async Task<IActionResult> StudentLogin()
        {
            var students = from m in _context.Student
                           select m;

            return View(await students.ToListAsync());
        }

        private string UploadedFile(StudentViewModel model)
        {
            string uniqueFileName = null;

            if (model.ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.ProfileImage.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfileImage.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

RSWEB_project/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RSWEB Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-controller="Home" asp-action="Index">RSWEB Project</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Students" ? "font-weight: bold;" : "")"
                               asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Teachers" ? "font-weight: bold;" : "")"
                               asp-controller="Teacher" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Courses" ? "font-weight: bold;" : "")"
                               asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Enrollments" ? "font-weight: bold;" : "")"
                               asp-controller="Enrollment" asp-action="Index">Enrollments</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    

    <div style="padding-bottom: 80px;"> <!--for the footer (footer is fixed and height is 60px)-->
        @RenderBody()
    </div>


    <footer class="footer border-top text-muted">
        <div class="container">
            &copy; 2020 - RSWEB Project/Workshop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

RSWEB_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RSWEB Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-controller="Home" asp-action="Index">RSWEB Project</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Students" ? "font-weight: bold;" : "")" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Teachers" ? "font-weight: bold;" : "")" asp-controller="Teacher" asp-action="Index"> Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Courses" ? "font-weight: bold;" : "")" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-left: 20px; @(ViewData["CurrentPage"] as string == "Enrollments" ? "font-weight: bold;" : "")" asp-controller="Enrollment" asp-action="Index">Enrollments</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    

    <div style="margin-bottom: 80px;"> <!--for the footer (footer is fixed and height is 60px)-->
        @RenderBody()
    </div>


    <footer class="footer border-top text-muted">
        <div class="container">
            &copy; 2020 - RSWEB Project/Workshop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

RSWEB_project/Views/Shared/_NonAdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RSWEB Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-controller="Home" asp-action="Index">RSWEB Project</a>

                @if (ViewData["ProfilePicture"] != null)
                {
                    <div style="height: 100%;">
                        <img src="~/images/@ViewData["ProfilePicture"]" style="height: 40px; border-radius: 20px;" />
                        <span style="color: gray;">&nbsp;@ViewData["FullName"]</span>
                    </div>
                }

            </div>
        </nav>
    </header>


    <div style="padding-bottom: 80px;">
        <!--for the footer (footer is fixed and height is 60px)-->
        @RenderBody()
    </div>


    <footer class="footer border-top text-muted">
        <div class="container">
            &copy; 2020 - RSWEB Project/Workshop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>